from app.modules.auth.schemas import LoginRequest, UserCreate, UserRead, UserRoleUpdate
from app.modules.catalog.schemas import (
    CategoryCreate,
    CategoryRead,
    IngredientCreate,
    IngredientRead,
    PriceCreate,
    PriceRead,
    StoreCreate,
    StoreRead,
    Unit,
)
from app.modules.inventory.schemas import InventoryCreate, InventoryRead
from app.modules.planner.schemas import (
    DayEntryCreate,
    DayResponse,
    DayUpdateRequest,
    GenerateWeekRequest,
    MealPlanEntryRead,
    PlannerResponse,
)
from app.modules.recipes.schemas import (
    MealSlot,
    MissingIngredientRead,
    RecipeCreate,
    RecipeIngredientCreate,
    RecipeIngredientRead,
    RecipeRead,
)
from app.modules.shopping.schemas import (
    ShoppingGenerateRequest,
    ShoppingItemCreate,
    ShoppingItemPatch,
    ShoppingItemRead,
    ShoppingListResponse,
)

__all__ = [
    "CategoryCreate",
    "CategoryRead",
    "DayEntryCreate",
    "DayResponse",
    "DayUpdateRequest",
    "GenerateWeekRequest",
    "IngredientCreate",
    "IngredientRead",
    "InventoryCreate",
    "InventoryRead",
    "LoginRequest",
    "MealPlanEntryRead",
    "MealSlot",
    "MissingIngredientRead",
    "PlannerResponse",
    "PriceCreate",
    "PriceRead",
    "RecipeCreate",
    "RecipeIngredientCreate",
    "RecipeIngredientRead",
    "RecipeRead",
    "ShoppingGenerateRequest",
    "ShoppingItemCreate",
    "ShoppingItemPatch",
    "ShoppingItemRead",
    "ShoppingListResponse",
    "StoreCreate",
    "StoreRead",
    "Unit",
    "UserCreate",
    "UserRead",
    "UserRoleUpdate",
]
